### ISSUE TITLE
Eddystone support

### ISSUE THREAD

**Issue by rrjanbiah** [MacKentoch/reactNativeBeaconExample#3]
Can you please provide some hint on how we can add support for Eddystone? TIA

**Comment by MacKentoch** [comment]
Hi @rrjanbiah 

Yes but it will demand a bit more time.

I take care of [`react-native-beacons-manager`](https://github.com/MacKentoch/react-native-beacons-manager). I want it nice and simple and then full featured (*Eddystone, Nordic beacons etc...*)

I plan to [add Eddystone support in v1.1.0](https://github.com/MacKentoch/react-native-beacons-manager/issues/3) (*just need to fix few issues so library basis are clean to add more features*).

Until that you can have a look of [documentation and tips around this library](https://github.com/MacKentoch/react-native-beacons-manager/tree/master/examples/samples#detailed-documentation--sample-code) I just added.

**Comment by MacKentoch** [comment]
I close this issue here since it is related the #3 if react-native-beacons-manager.

Feel free to follow there.

**Comment by rrjanbiah** [comment]
@MacKentoch Thank you
